# Generated by Django 2.2.1 on 2019-05-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_title', models.CharField(blank=True, max_length=64, null=True)),
                ('todo_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
